apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-prometheus-exporter
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-prometheus-exporter
      annotations:
        kubearmor-policy: audited
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      containers:
      - name: kubearmor-prometheus-exporter
        image: kubearmor/kubearmor-prometheus-exporter:latest
        env:
        - name: KUBEARMOR_SERVICE
          value: kubearmor.kube-system.svc:32767
        ports:
        - containerPort: 9100
